version: '3.9'

volumes:
  postgres2: {}

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=DB_PASSWORD
      - POSTGRES_USER=DB_USER
      - POSTGRES_DB=DB_NAME